# TODO: SAVE CONFIG FILE IN THE LOGS
[run]
  model_used = 'fasttext'  # 'fasttext', 'glove', 'elmo', 'bert'
  model_id = 'test'
  ngram_len = 3  # 0 for word encoding, > 0 for subword encoding
  debug_mode = false
  load_model = false
  load_tokenizer = true
  num_workers = 0  # TODO: check for potential issues with iter-style dataset for num_workers > 0
  pin_memory = false

[data]
  data_dir = '/mnt/d/DL/datasets/autophe/json'  # '/mnt/d/DL/datasets/autophe/json', './data/json'
  data_subdir = 'time_not_categorized'
  log_dir = './logs'
  max_seq_len = 512
  # [data.special_tokens]
  #   ':OK' = 101
  #   ':AB' = 102

[train]
  lr = 2.0
  adam_betas = [0.9, 0.998]
  accumulate_grad_batches = 1
  max_tokens_per_batch = 4096
  n_steps = 100000
  n_warmup_steps = 10000

[models]
  [models.fasttext]
    task = 'skipgram'  # 'cbow'?
    input_keys = ['center']
    label_keys = ['context']
    d_embed = 256
    [models.fasttext.special_tokens]
      '[PAD]' = 0
      '[UNK]' = 1

  [models.glove]
    task = 'cooc'
    input_keys = ['left', 'right']
    label_keys = ['cooc']
    d_embed = 256
    [models.glove.special_tokens]
      '[PAD]' = 0
      '[UNK]' = 1
      
  [models.bert]
    task = 'mlm'
    input_keys = ['masked']
    label_keys = ['masked', 'target']
    n_layers = 4
    d_embed = 256
    d_ff = 2048
    n_heads = 8
    dropout = 0.1
    [models.bert.special_tokens]
      '[PAD]' = 0
      '[UNK]' = 1
      '[CLS]' = 2
      '[SEP]' = 3
      '[END]' = 4
      '[MASK]' = 5
